name: flutter_app_demo01
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  english_words: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: ^0.1.2
  event_bus: ^1.0.1
  fluro: ^1.3.4
  image_picker: ^0.4.10
  sqflite: ^0.12.1
  flutter_markdown: ^0.2.0
  url_launcher: ^4.0.1
      # 本地存储、收藏功能
  shared_preferences: ^0.4.3
  dio: ^1.0.6
  flutter_webview_plugin: ^0.3.0+2
      # 日期格式化
  intl: 0.15.7
  city_pickers: ^0.1.0
  flutter_staggered_grid_view: ^0.2.7
  fish_redux: ^0.1.1

flutter:
  uses-material-design: true
  assets:
   - images/lake.png




