name: flutter_app_demo01
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  english_words: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
   - family: MyCustomFont
     fonts:
       - asset: fonts/FZLanTingHeiS-L-GB-Regular.ttf
       - weight: FontWeight.bold



